### ISSUE TITLE
Releasing connection reference too early in a channel leads to a segmentation fault

### ISSUE THREAD

**Issue by zerkms** [php-amqplib/php-amqplib#415] opened 2016-06-28 00:08 UTC
The current channel implementation looks like this:

``` php
    public function channel($channel_id = null)
    {
        if (isset($this->channels[$channel_id])) {
            return $this->channels[$channel_id];
        }

        $channel_id = $channel_id ? $channel_id : $this->get_free_channel_id();
        $ch = new AMQPChannel($this->connection, $channel_id);
        $this->channels[$channel_id] = $ch;

        return $ch;
    }
```

So as we can see - it does not hold a reference to the connection object but to its `connection` member.

This leads to sporadic segfaults.

And the reason is simple:

Say you have a code like this:

``` php
    private function getClient(array $config)
    {
        $credentials = $config['credentials'];

        $conn = new AMQPStreamConnection($credentials['host'], $credentials['port'], $credentials['username'], $credentials['password'], '/');
        $ch = $conn->channel();
        $ch->basic_qos(null, 1, null);

        return $ch;
    }
```

From here - the `$conn` instance becomes garbage-collectible after you return from the function (it's not referred by any other object).

So if at any moment php's GC decides to collect it - it invokes its destructor

``` php
    public function __destruct()
    {
        if ($this->close_on_destruct) {
            $this->safeClose();
        }
    }
```

and then when the channel next time tries to read from the socket - it segfaults, since it tries to read from an unmanaged resource.

Solution: a channel **MUST** retain a reference to the connection object to prevent it from being garbage collected.

PS: I commented on https://github.com/php-amqplib/php-amqplib/issues/261 but I believe the problem should be addressed explicitly as a separate issue.

**Comment by michaelklishin** [comment] 2016-06-28 00:34
Thank you for providing the much needed details.

**Comment by andreyrevinate** [comment] 2016-07-05 17:13
I think I have a tweak that fixes this issue. Please try this: https://github.com/php-amqplib/php-amqplib/pull/419

**Comment by zerkms** [comment] 2016-07-05 21:12
@andreyrevinate it has nothing to do with this problem surely.

This issue report is about losing a reference and a premature garbage collection, which your code does not affect in any way.

**Comment by andreyrevinate** [comment] 2016-07-06 08:29
Well, I tried your suggested way of fixing that - it did not helped with segmentation fault. The tweak I suggest just solves the segmentation fault issue, it has nothing to do with garbage collection.

**Comment by zerkms** [comment] 2016-07-06 08:38
> it has nothing to do with garbage collection.

I have created stack traces and I explored the core dump files. So I have proofs that it does.

But whatever, I won't argue with you.

**Comment by zerkms** [comment] 2016-07-06 08:40
@andreyrevinate 

> I tried your suggested way of fixing that

out of curiosity, what *exactly* did you try?

**Comment by andreyrevinate** [comment] 2016-07-06 13:25
Yes, sorry, I meant that my fix is nothing to do with garbage collection. Your issue title has 2 parts: 
* Segmentation fault
* reference to connectoin must be hold by a channel

my fix is only for first part - it fixes segmentation fault. 

> out of curiosity, what exactly did you try?
I tried keeping the reference to the parent (container) object, which is $this in the very first piece of code that is in the issue description.
I'll try to commit it to another branch within few days.

**Comment by zerkms** [comment] 2016-07-06 21:11
@adrienbrault that's interesting. Where did you put that reference to? As an arbitrary member of `$ch` variable?

**Comment by andreyrevinate** [comment] 2016-07-06 21:38
Yes, in this line: 
> $ch = new AMQPChannel($this->connection, $channel_id);
I passed $this instead of $this->connection, and inside AMQPChannel::_construct I saved both $this and $this->connection as different properties. I also made sure, that optimizer does not optimize too much by making dummy branches in AMQPChannel code echoing different things depending on both these properties.

**Comment by zerkms** [comment] 2016-07-06 21:42
Yep. So apparently what you experienced was caused by something else.

**Comment by andreyrevinate** [comment] 2016-07-07 06:47
Can you, please, test if you still experience segfaults with the tweak I made?

**Comment by jeffreydwalter** [comment] 2016-08-05 19:50
I can confirm that those changes fix the seg faults for me.

**Comment by jeffreydwalter** [comment] 2016-08-08 16:15
I personally don't think a circular reference to the connection from the channel here makes sense. @zerkms you're just not using the API properly. You could easily just return the channel and connection from your function. Even better might be to just hold a reference to the connection in your class as an instance variable.

`private function getClient(array $config)
    {
        $credentials = $config['credentials'];
        $client = [];
        $client['conn'] = new AMQPStreamConnection($credentials['host'], $credentials['port'], $credentials['username'], $credentials['password'], '/');
        $client['channel'] =  $client['conn']->channel();
        $client['channel']->basic_qos(null, 1, null);

        return $client['channel'];
    }`

**Comment by zerkms** [comment] 2016-08-08 21:28
@jeffreydwalter that's what I exactly do as a *workaround*, but I personally still think that in a language with automatic memory management - under no circumstances the object must become eligible for GC until any of unmanaged resources it owns are in use by someone else.

> I personally don't think a circular reference to the connection from the channel here makes sense.

Exactly. From the design point of view it makes no sense to have a client that holds a connection as its member and inherits from a connection class.

**Comment by UlrichKu** [comment] 2016-08-10 12:54
Hi.
I _think_ I have either the same or a very similar problem: Segmentation fault (SIGSEGV) when the destructor of a connection is called.

I don't know - even after a few hours of debugging - why this really happens.
The problematic statement seems to be `if (!$this->protocolWriter || !$this->isConnected())` in AbstractConnection->close(); Changing that to `empty(...)` makes this location work but it then fails at some later point.

A few interesting observations though:
- This only happens in the context of our Behat tests
- And it only happens in the context of the connection being closed from the destructor (closing it manually after usage everything works)
- Any crash can also be avoided if the connection is not closed (ie `set_close_on_destruct(false)`)

**Comment by andreyrevinate** [comment] 2016-08-10 12:57
> Changing that to empty(...) makes this location work but it then fails at
some later point.
Please share this later point. For us changing it to empty made things work
without any segfaults. There is a php bug making segfault in particular
case when gc is calling destructor. It is intermittent, because gc wakes up
only time to time, but it can be triggered when you launch gc manually.

AG

**Comment by UlrichKu** [comment] 2016-08-10 13:06
> Please share this later point.

That one is not really easy to pinpoint then.
But I can try if this seems to be important.
In any of these cases however I don't see the difference in a working close (when doing it manually) and one that crashes.

> because gc wakes up only time to time, but it can be triggered when you launch gc manually.

Maybe it is a bit different for me: With our Behat tests this is very reproducible and happens always at the same time.
This however doesn't seem to be a meaningful location: The statement before the destructor is called is some totally unrelated code (doing a count(array) at the time).

But this is a segmentation fault so everything around it could be a random conincidence?

**Comment by jaffacake** [comment] 2016-10-06 15:56
We also experienced the same thing recently as we send multiple messages in a long running script 30 - 60 seconds. We had about 7 or 8 segmentation faults in a 24 hour period.

I had to force the connection & channel to close after sending the message. To avoid my classes being misused (ie. trying to same multiple messages with the same queue instance) I had to add automatic reconnect logic. This really needs to be fixed, it feels like I'm having to write a lot of code to workaround a flaw in the library.

**Comment by velovint** [comment] 2016-11-23 01:47
Here is a simplest code to reproduce segfault
```php
<?php
require_once "vendor/autoload.php";

new PhpAmqpLib\Connection\AMQPStreamConnection("localhost", 5672, "user", "user");
gc_collect_cycles();
```

PR #419 resolves segfaults for me. Thank you @dc-adenisov

**Comment by elicoten** [comment] 2017-07-18 10:15
We have been experiencing segfaults on PHP 5.6 when creating lots of these AMQP connections and then removing the references to them.

We think believe it may be related to these bugs one of which the PHP team have declined to fix:
https://bugs.php.net/bug.php?id=72870
https://bugs.php.net/bug.php?id=72286

We are considering using the AMQP channels/connections as singletons instead to avoid the problem.

**Comment by michaelklishin** [comment] 2017-07-18 11:03
This library has no native code and cannot be considered a root cause for segfaults. @elicoten having multiple connections in general is not discouraged. I wonder if your PHP process runs out of file descriptors in some cases and that trips up the runtime resulting in a segfault? http://www.rabbitmq.com/networking.html has some relevant information.

**Comment by elicoten** [comment] 2017-07-18 12:05
@michaelklishin Of course the root cause lies with PHP itself, I just left a comment here:
1. In case someone wants to suggest code for a workaround within the library (apparently not, which is fine)
2. As an aid for anyone else who encounters the same problem that if you are using the library in the way we were - creating new instances for each use - with PHP < 7, then there is a possibility they will encounter this bug.

In terms of mulitple connections - they would normally be successive (rather than concurrent but if that's not the way this library was intended to be used, then in a way that's also good to know.

As an aside, we tried with HHVM which didn't suffer from this problem.

**Comment by zerkms** [comment] 2017-07-18 20:02
> This library has no native code and cannot be considered a root cause for segfaults.

Well, if you check my initial post with detailed explanation and the solution you would see - that there is still bug in the library about re-using the closed network socket.

It **IS** wrong to read from the closed socket.

**Comment by michaelklishin** [comment] 2017-07-18 20:54
@zerkms thanks for the explanation. If you understand the problem well, please submit a PR. Evaluating a PRs for a well researched issue should not take long.

**Comment by zerkms** [comment] 2017-07-18 21:02
The problem is easy to explain, the solution is not that easy: the current design has soldered the connection and the channel together. So fixing it properly would require a significant amount of redesign to be done.

In short:

```php
$ch = new AMQPChannel($this->connection, $channel_id);
```
from the `AbstractConnection::channel` method should accept `$this`, not `$this->connection` and deal with the connection object not with the reference to another connection object `$this` holds (here is a place where it becomes tangled: a connection object that does not hold a socket has a reference to another connection object that does hold a socket).

**Comment by michaelklishin** [comment] 2017-07-18 21:29
@zerkms makes sense. That's a reasonable change (and not the most drastic API change), so let's see if someone would be interested in giving it a shot.

**Comment by zerkms** [comment] 2017-07-18 21:52
I would have invested time if it was not a simple workaround available (in the initial post as well), since I don't use rabbitmq much enough for this to bother me enough to spend the company time for contributing here. Sorry :-(

**Comment by mledoze** [comment] 2017-11-27 08:43
> Any crash can also be avoided if the connection is not closed (ie set_close_on_destruct(false))

I can confirm that the workaround proposed by @UlrichKu work (tested with version 2.6.3)

**Comment by lukebakken** [comment] 2018-10-09 15:37
Closing and assuming that #419 fixed this issue. Please test with `2.8.0` RC1 that will be available this week.

**Closed by lukebakken** 2018-10-09 15:37 UTC
