### ISSUE TITLE
Error reading data. Recevived 0 instead of expected 1 bytes

### ISSUE THREAD

**Issue by anki-code** [php-amqplib/php-amqplib#72] opened 2013-03-14 14:51 UTC
Hi, when I try to run 

```
videlalvaro/php-amqplib/demo/amqp_consumer.php
```

I've got the error after process completed:

```
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error reading data. Received 0 instead of expected 1 bytes' in /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:50
Stack trace:
#0 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\IO\StreamIO->read(1)
#1 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(145): PhpAmqpLib\Wire\AMQPReader->rawread(1)
#2 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(236): PhpAmqpLib\Wire\AMQPReader->read_octet()
#3 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(264): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(111): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(207): PhpAmqpLib\Channel\AbstractChannel->next_fram in /application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 50
```

What's the problem? Help me please.

**Comment by oriolgm** [comment] 2015-08-10 10:59
We also had this issue and it was related with the setup of the HAProxy. It was closing the connections after a short period of time. The solution were found by reading this post:

https://deviantony.wordpress.com/2014/10/30/rabbitmq-and-haproxy-a-timeout-issue/

Hope this helps

**Comment by rskanron** [comment] 2015-12-11 18:32
I get this issue when using heartbeats if the process runs over the heartbeat timeout. I'm not sure why it would try reading again without checking the heartbeat first. Actually, I would think there would be an error when trying to ack the message but the connection is closed.

**Comment by nubeiro** [comment] 2016-02-21 18:01
Is this still an issue? I can't reproduce the problem.

**Comment by krzysztof-gzocha** [comment] 2016-03-14 11:27
For me the problem was missing `mbstring` extension..

**Comment by nubeiro** [comment] 2016-03-14 12:24
mbstring extension is already required in composer.json file, so it should not be an issue anymore.

**Closed by nubeiro** 2016-03-14 12:24 UTC
Labels: waiting

**Comment by taozywu** [comment] 2016-04-27 08:05
@anki-code   do you have solved your problem ?

i can give u one idea ... see your username and password   or vhost

**Comment by topikito** [comment] 2016-05-18 15:17
Just for the record, as @krzysztof-gzocha said, I installed the extension and that fixed my issue.

The `polyfill` was triggering a `Notice`:
```
PHP Notice:  iconv_strlen(): Detected an illegal character in input string in …/vendor/symfony/polyfill-mbstring/Mbstring.php on line 338
```

Which contains:
```
    public static function mb_strlen($s, $encoding = null)
    {
        $encoding = self::getEncoding($encoding);
        var_dump($s);

        return iconv_strlen($s, $encoding);
    }
```
Doing a `var_dump` on `$s`:
```
string(14) "\000\000\000\000�\000
\000
\000	\000"
```

Which explains my issue - In case anyone else gets the same due to this reason.

**Comment by stof** [comment] 2016-05-18 16:03
@topikito please open an issue on the symfony/polyfill repository, as this looks like a bug in the polyfill which should be fixed.

**Comment by krzysztof-gzocha** [comment] 2016-05-18 16:06
@stof in my situation there was just an missing extension and polyfill was working fine.
If @topikito didn't actually have it installed before then I assume everything is correct.

**Comment by topikito** [comment] 2016-05-18 17:01
Done @stof https://github.com/symfony/polyfill/issues/63

**Comment by michaelperrin** [comment] 2016-09-21 17:55
I get this error too (`Error reading data. Recevived 0 instead of expected 7 bytes`) although:

* The `mbstring` extension is installed
* My `host`, `port`, `user`, `password`, `vhost` configuration are correct
* I'm using a RabbitMQ version (3.6.5)

The messages are consumed, but this error is shown.

I'm using RabbitMQ 3.6.5 in a Docker container. PHP is running in a PHP 7 Docker container.

I have not found the problem yet, but I'll try to investigate more. If someone has an idea that would be appreciated.

**Comment by taozywu** [comment] 2016-09-22 01:09
@michaelperrin  
you must look Virtual Hosts set, Including the permissions.
and you can follow this link for your problem
1. https://github.com/php-amqplib/php-amqplib/issues/72
2.stackoverflow

at last good luck!

**Comment by michaelperrin** [comment] 2016-09-22 14:21
@taozywu Thanks for the help. Unfortunately I had to ask on StackOverflow, as I didn't find any solution (http://stackoverflow.com/questions/39640489/error-reading-data-while-executing-a-rabbitmq-consumer-in-symfony).

**Comment by jhonatanTeixeira** [comment] 2017-04-26 22:37
AbstractConnection.php
```php
protected function wait_frame($timeout = 0)
    {
        if (is_null($this->input))
        {
            $this->setIsConnected(false);
            throw new AMQPRuntimeException('Broken pipe or closed connection');
        }

        $currentTimeout = $this->input->getTimeout();
        $this->input->setTimeout($timeout);

        try {
            // frame_type + channel_id + size
            $this->wait_frame_reader->reuse(
                $this->input->read(AMQPReader::OCTET + AMQPReader::SHORT + AMQPReader::LONG)
            );

            $frame_type = $this->wait_frame_reader->read_octet();
            $class = self::$PROTOCOL_CONSTANTS_CLASS;
            if (!array_key_exists($frame_type, $class::$FRAME_TYPES)) {
                throw new AMQPRuntimeException('Invalid frame type ' . $frame_type);
            }
            $channel = $this->wait_frame_reader->read_short();
            $size = $this->wait_frame_reader->read_long();

            // payload + ch
            $this->wait_frame_reader->reuse($this->input->read(AMQPReader::OCTET + (int) $size));

            $payload = $this->wait_frame_reader->read($size);
            $ch = $this->wait_frame_reader->read_octet();

        } catch (AMQPTimeoutException $e) {
            $this->input->setTimeout($currentTimeout);
            throw $e;
        }

        $this->input->setTimeout($currentTimeout);

        if ($ch != 0xCE) {
            throw new AMQPRuntimeException(sprintf(
                'Framing error, unexpected byte: %x',
                $ch
            ));
        }

        return array($frame_type, $channel, $payload);
    }
```

SocketIO.php
```php
    public function read($n)
    {
        $res = '';
        $read = 0;

        $buf = socket_read($this->sock, $n);
        while ($read < $n && $buf !== '' && $buf !== false) {
            // Null sockets are invalid, throw exception
            if (is_null($this->sock)) {
                throw new AMQPRuntimeException(sprintf(
                    'Socket was null! Last SocketError was: %s',
                    socket_strerror(socket_last_error())
                ));
            }

            $read += mb_strlen($buf, 'ASCII');
            $res .= $buf;
            $buf = socket_read($this->sock, $n - $read);
        }

        if (mb_strlen($res, 'ASCII') != $n) {
            throw new AMQPIOException(sprintf(
                'Error reading data. Received %s instead of expected %s bytes',
                mb_strlen($res, 'ASCII'),
                $n
            ));
        }

        return $res;
    }
```

As you can see, AMQPReader::OCTET + AMQPReader::SHORT + AMQPReader::LONG = 7.

this value will be passed to the read function wich will try to read from a socket and according to php documentation:
"socket_read() returns a zero length string ("") when there is no more data to read."

when the queue is empty and rabbit returns nothing a empty string is return from socket_read wich is not 7 bytes long, then the error occurs. its a bug, i dont have time to solve it right now and make a MR, and i'm using stream instad, but thats a shame since sockets are much faster and i needed speed.

**Comment by m0onspell** [comment] 2017-05-23 20:59
@michaelperrin thank you, answer on stackoverflow fixed my issue. But does that means that we basically unable to use sockets? Isn't it a bug?

**Comment by michaelperrin** [comment] 2017-05-23 21:01
@m0onspell This is probably a bug indeed, but I didn't manage to find what was wrong... That's too bad as the use of sockets would probably result in better performance.

**Comment by m0onspell** [comment] 2017-05-23 21:10
@michaelperrin 
https://github.com/php-amqplib/RabbitMqBundle/issues/447
Let's see.

**Comment by jhonatanTeixeira** [comment] 2017-05-23 21:16
For me, this problem is impacting consumers only, so i've created 2
connections on the config, for producers i use sockets, since my producers
are called during online calls to my api im getting the performance benefit
of the socket.

The consumers are using streams, but thats not a big problem since i can
scale them on a fair dispatching fashion.

2017-05-23 18:01 GMT-03:00 Michaël Perrin <notifications@github.com>:

**Comment by Ocramius** [comment] 2018-01-24 10:19
@michaelperrin I think this got solved via https://github.com/php-amqplib/php-amqplib/pull/448
