### ISSUE TITLE
php-amqp AMQPStreamConnection abstraction class constructor sets heartbeat = 0, keepalive = false

### ISSUE THREAD

**Issue by ghost** [php-amqplib/php-amqplib#374] opened 2016-02-18 20:08 UTC
Documentation at http://www.rabbitmq.com/configure.html (see: heartbeat) describes the default as being set to 60 seconds:

> Value representing the heartbeat delay, in seconds, that the server sends in the connection.tune frame. If set to 0, heartbeats are disabled. Clients might not follow the server suggestion, see the AMQP reference for more details. Disabling heartbeats might improve performance in situations with a great number of connections, but might lead to connections dropping in the presence of network devices that close inactive connections.
> Default: 60 (580 prior to release 3.5.5)

The code in the abstraction constructor, invoked from AMQPSSLConnection class, defaults the connection option for heartbeat to zero.  If php-amqplib is to be in-alignment with the RMQ doc, then the heartbeat value should be set to 60 and keepalive set to true.

once I passed the keepalive/heartbeat values when instantiating an SSL connection, I could no longer reproduce the idle-timeout event between services connecting across domains.

**Comment by d3xt3r01** [comment] 2016-02-18 20:25
How did you pass the keepalive/heartbeat values ? I have an issue making it work at all when using keepalive/heartbeat. Can you share a code snippet ?

**Comment by mshallop** [comment] 2016-02-18 20:55
I saw your report - I, too, am using SSL - I pull my run-time config values out of an xml file I keep.

I put echo statements in the file:

./lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php

after line 157 to echo the heartbeat setting when I start-up the broker services to confirm the new heartbeat value.   We were able to provoke timeout errors after waiting an hour or so after the brokers started and remained idle.   After I put in the new options when instantiating the AMQPSSLConnection class, I've been unable to reproduce the timeout.

CONFIG_BROKER_KEEP_ALIVE is a constant:  "keepalive"
CONFIG_BROKER_HEARTBEAT is a constant: "heartbeat"


Hope this helps you - best of luck!

```
    private static function getBrokerResource()
    {
        if ((self::$resourcePool[RESOURCE_BROKER] === null) and (!empty(self::$cfgBroker))) {
            if (self::$cfgBroker[CONFIG_BROKER_USE_SSL]) {
                $user = self::$cfgBroker[STRING_USER];
                $pass = self::$cfgBroker[STRING_PASSWORD];
                $host = self::$cfgBroker[STRING_HOST];
                $port = self::$cfgBroker[STRING_PORT];

                $options[ CONFIG_BROKER_KEEP_ALIVE ] = self::$cfgBroker[CONFIG_BROKER_KEEP_ALIVE];
                $options[ CONFIG_BROKER_HEARTBEAT ]  = self::$cfgBroker[CONFIG_BROKER_HEARTBEAT];
                if (!static::checkCerts()) return;

                // build the ssl-options array and request a broker resource from the resource manager
                try {
                    $ssl_opts = [STRING_CA_FILE => static::$caFile, STRING_LOCAL_CERT => static::$certFile];
                    static::$resourcePool[RESOURCE_BROKER] = new AMQPSSLConnection($host, $port, $user, $pass, '/', $ssl_opts, $options);
                    static::$brokerAvailable = is_object(self::$resourcePool[RESOURCE_BROKER]);
                    if (static::$loggerAvailable) pgsError::set(ERROR_INFO, SUCCESS_CONNECTED . RESOURCE_BROKER);
                } catch (Exception $e) {
                    pgsError::set(ERROR_FATAL, $e->getMessage());
                    static::$brokerAvailable = false;
                    if (static::$loggerAvailable) pgsError::set(ERROR_FATAL, ERROR_RESOURCE_404 . RESOURCE_BROKER);
                    echo '[' . date("d/m/y@H:i:s", time()) . '] [ X]' . COLON . ERROR_RESOURCE_404 . RESOURCE_BROKER . static::$eos;
                }
            } else {
                pgsError::set(ERROR_FATAL, ERROR_SSL_REQUIRED);
                static::$brokerAvailable = false;
            }
        }
    }
```

**Comment by d3xt3r01** [comment] 2016-02-18 21:11
Yeah, as I thought .. all I'd need is an array("keepalive" => true, "heartbeat" => 30) .. no luck for me. it just disconnects.

```
 [x] AMQPTimeoutException Error sending data. Socket connection timed out
```

**Comment by mshallop** [comment] 2016-02-18 22:21
Were are you trapping that exception?

**Comment by mshallop** [comment] 2016-02-19 19:54
Some more information...

this fail is happening on a local aws instance... I have a second rmq cluster set-up in our data-center to handle remote requests.  The requests sent from aws are built at the time of the request, a client is instantiated, and the the request is published to the remote queue.  Between aws and the data center, there is no persistent (permanent) connection.

When the brokers have been inactive for at least 90 minutes, the node.js connection will crash the php consumer/broker/daemon (RPC queue) on the other end depositing this gem in the php_errors log:


> [19-Feb-2016 11:38:42 America/Los_Angeles] PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:190
> Stack trace:
> #0 /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(336): PhpAmqpLib\Wire\IO\StreamIO->write('?????????????')
> #1 /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(457): PhpAmqpLib\Connection\AbstractConnection->write('?????????????')
> #2 /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(223): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
> #3 /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(259): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
> #4 /home/atladmin/aura-ds/lib/vendor/videla in /home/atladmin/aura-ds/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 190

My PHP broker dies on this event, and there's no error in the amqp logs.

node.js logs: when the node client does not get a connection response within five seconds, it considers the non-response as a time out and cleans the reply queue.

> Client: Connecting to RabbitMQ server
> Client: Error: RPC Reply Timeout
> at null._onTimeout (/home/atladmin/ome-forebrain/ome-user-service/node_modules/ome-common/lib/dapi-client.js:86:29)
> at Timer.listOnTimeout (timers.js:92:15)

Note that, if there's activity on the queue, from any origin, we cannot reproduce this issue.  It's only after the system's been at quiet state for around 90 minutes can we replicate.

**Comment by mshallop** [comment] 2016-03-08 18:06
Kind of a final comment here about the issue - 

This problem with keepAlive over SSL isn't a problem with the php-amqp library - it's a known bug in the PHP [socket_import_stream](http://php.net/manual/en/function.socket-import-stream.php) function - in that the function does not support SSL connections.  

lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php

line 305: 
Resource should be evaluated prior to making the call to ensure you're not attempting to enable a keepAlive over SSL.
PHP Warning:  socket_import_stream(): cannot represent a stream of type tcp_socket/ssl as a Socket Descriptor

line 306:
PHP Warning:  socket_set_option() expects parameter 1 to be resource, boolean given...
Return values from socket_import_stream() should be checked and, if null or false, then socket_set_option should not be called.  Both of these lines/calls generate avoidable PHP warnings.

**Comment by postalservice14** [comment] 2016-03-19 19:41
@mshallop Are you able to open a PR for this?

**Comment by mshallop** [comment] 2016-03-19 22:22
@postalservice14 Assuming you mean "Problem Report" -- isn't this it?

thanks!

**Comment by postalservice14** [comment] 2016-03-20 02:18
@mshallop Sorry, no I mean Pull Request.

**Comment by mshallop** [comment] 2016-03-21 19:51
@postalservice14 
Hey John, 
Sorry - just no light-bulb love here for me.  Why/when would I file a pull request if I've not  forked and/or modified the code base?  Does this serve as a bug-report for you and the team?

thanks!
--mike

**Comment by postalservice14** [comment] 2016-03-22 21:56
Hey Mike,

No problem.  The idea behind open-source software is that the community contributes code (if they are able).  They do that through pull requests.  I was just asking if you were able to provide a fix for this via a pull request.  If you're not, that's fine.  Someone from the community or myself is free to open a pull request to improve the error checking in this scenario, it may just take time.  That's why I was just asking if you were able to contribute that fix.

Thanks.

**Comment by mshallop** [comment] 2016-03-23 17:15
Morning John, 

I understand.  I don't think I have a fix for anything other than suppressing warnings and that didn't warrant a pull, imo.  

There's a suggested fix on the php.net web page that provides an alternative for socket_import_stream() to establish a secure connection allowing heartBeat to work, but I'd be a bit over my head in terms of validating or unitTesting within your code base.

That's why no pull.  Well, that and I'm already 60+ hour/week into my own code base...

Much respect!

-mike

**Comment by postalservice14** [comment] 2016-03-30 17:41
I'm not sure what the rationale for setting the heartbeat default to 0 was, that was before my involvement with the library.  To be honest, I agree, that it should probably be defaulted to 60 seconds, but that would be a backwards compatibility break.  Clients not expecting a heartbeat, will all of a sudden get one.  So I'm going to put this in the 3.x milestone for now.

As a workaround, if you want a heartbeat, you do need to set it manually.  Even more confusing, if you set the heartbeat value to `null`, it will use the value from the server. :-/  I know, pretty confusing.

**Comment by michaelklishin** [comment] 2016-03-30 19:41
@postalservice14 `0` means "no heartbeats", I see no upside to having that. This setting affects only *this specific* client and RabbitMQ, it cannot affect other libraries. Anyhow, if a client does not support heartbeats, we'd consider it to be broken.

**Comment by ramunasd** [comment] 2019-03-19 12:37
Yet another forgotten issue :)
@lukebakken seems like we fixed default heartbeat value and keepalive is not allowed for ssl connections anymore. Can we include into 2.9.0 and close this one?

**Comment by lukebakken** [comment] 2019-03-19 15:30
Oh yes since we have set a non-`0` heartbeat value this can be closed. Thanks for noticing.

**Closed by lukebakken** 2019-03-19 15:30 UTC
Labels: enhancement
