### ISSUE TITLE
Invalid frame type 65

### ISSUE THREAD

**Issue by dbu** [php-amqplib/php-amqplib#437] opened 2016-09-19 15:37 UTC
we occasionally see this exception in our logs. any idea what could lead to a frame type 65?

```
/srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:514
Stack trace:
#0 /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#1 /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#2 /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#3 /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(170): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/BaseAmqp.p in /srv/www/vhosts/api/releases/20160914123155/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 514
```

**Comment by vitorsdcs** [comment] 2016-09-19 21:54
I'm running into a similar issue... "Invalid frame type 72"

**Comment by splio-aleroux** [comment] 2016-09-27 15:11
I encounter the same issue, the octet that follows in this frame are 77,81,80
So we receive "AMQP"

The recent changes are :
* upgrade from php5.6 to php 7.0.11
* usage of RabbitMQ heartbeat

**Comment by splio-aleroux** [comment] 2016-09-27 15:22
The same issue occurs with php 5.6.20

**Comment by mdrost** [comment] 2016-10-08 10:55
Same here. Our RPC client throws this exception and on reconnect hangs.

**Comment by splio-aleroux** [comment] 2016-10-08 12:35
As php is a synchronies language, heartbeat can't be supported easily. We "solved" the issue in PHP7 by catching the fatal errors/exception and then disconnect/reconnect to the AMQP server. It's kind of dirty ...

**Comment by splio-aleroux** [comment] 2016-10-08 12:36
Synchronous

**Comment by mdrost** [comment] 2016-10-09 15:10
I hope that this will help in something http://john.eckersberg.com/debugging-rabbitmq-frame_too_large-error.html

**Comment by mdrost** [comment] 2016-10-09 18:35
If heartbeat do disconnect/reconnect then all channels are closed but library still tries to read frames so it read protocol header.

**Comment by erikverheij** [comment] 2017-01-18 12:32
I got this error as well. In my case it was because I accidentally passed heartbeat as a string `"0"`. Passing it as an integer solved the bug for me.

**Comment by lukebakken** [comment] 2018-01-16 14:37
Please re-open this issue if you are still experiencing it and can provide code or instructions to reliably reproduce it. Thanks!

**Comment by MrSpoocy** [comment] 2018-02-12 15:55
This message comes also if you connect to the server , but use the wrong port. Than you only get the error "Invalid frame type 65".

**Comment by dbu** [comment] 2018-02-12 16:51
well, it mostly works on that port. maybe its networking problems and not the fault of this library. the error is not exactly helpful however, if it could identify that the server is not replying on this port or something like that, it would be easier to figure out what is going on...

**Comment by decrypted** [comment] 2018-04-09 10:36
have the same issue - doing async with heartbeat

Stack trace
…bstractConnection::wait_frame called at /xxxx
…/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/
AbstractChannel.php (225)
…/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/
AbstractChannel.php (335)
…Channel\AbstractChannel::wait called at xxxx/pull.php (306)

**Comment by decrypted** [comment] 2018-04-09 10:43
Reproduce could be to be REALLY busy for 2x more time before calling the socket again if heartbeat is enabled

**Comment by mollierobbert** [comment] 2018-10-10 09:35
@lukebakken Reproducing is quite simple. Set up a listener and sender with a 1s heartbeat configured on the connection.

Then, have the listener perform a task that takes too long:

```php
while (count($channel->callbacks)) {
    $channel->wait(null, true);
    sleep(3);
}
```

The second time we arrive at `wait()`, a `check_heartbeat()` will be performed that causes a `reconnect()` on the connection, since more than two seconds have passed (`heartbeat * 2 < time_since_last_read`).

However, as @splio-aleroux mentioned, the server will now push an 'AMQP' header, but the `wait()` call does not expect it. It reads the first byte `A` (decimal value 65) and throws an 'invalid frame type 65' exception.

With my limited knowledge on AMQP, I guess the solution would be for `check_heartbeat()` to not just reconnect the IO, but reconnect the connection itself which handles the protocol headers and such.

Still, the true solution is for the user to split their time-consuming job into smaller portions and send heartbeats between those chunks of work to ensure the connection is kept alive.

As a side note to this issue, the `$this->last_read && $this->last_write` check in `check_heartbeat()` should be rewritten to not check both values, since there are scenarios where there haven't been any reads yet but a heartbeat should still be issued once the method is called.

**Comment by lukebakken** [comment] 2018-10-10 14:06
@mollierobbert - thanks for the explanation. I might be able to get something in for `2.8.0`, but people should remember that heartbeats exist for a reason and not block them.

A PR to address `last_read` / `last_write` would be great. I am planning RC1 for version `2.8.0` this week.

If you're not already aware, this library is maintained on a volunteer basis so outside contributions are very welcome.

**Comment by mollierobbert** [comment] 2018-10-10 14:34
Thanks @lukebakken.

Agreed on the importance of having users implement heartbeats correctly. I'm not even sure if automatic reconnects are that great of a feature, considering it hides complexity the user should be aware of.

For example, a channel configured with message acknowledgements (`no_ack = false`) is required to keep the connection alive. If the library would silently reconnect, the client can no longer `ack` the message. They will face an 'unknown delivery tag' exception if they try to.

I digress. Thanks for your help - we'll try to contribute a PR for the `last_read` / `last_write` issue, for sure.

**Comment by makasim** [comment] 2018-11-26 10:39
More about the issue https://blog.mollie.com/keeping-rabbitmq-connections-alive-in-php-b11cb657d5fb.  

Reconnection is not a solution at all since all pre_fetched messages are marked as redelivered, that could lead a retry logic to be triggered. 

`enqueue/amqp-lib` fixes the issue using tick handler - https://github.com/php-enqueue/enqueue-dev/pull/658

**Comment by lukebakken** [comment] 2019-02-27 00:33
Reconnect was removed from the heartbeat check in #559. Please test the upcoming `2.9.0-rc1` release and make a note here if this issue persists.

**Closed by lukebakken** 2019-02-27 00:33 UTC
