### ISSUE TITLE
 Allowed memory exhausted in StreamIO.php when sig_handler traps SIGTERM

### ISSUE THREAD

**Issue by paericksen** [php-amqplib/php-amqplib#302] opened 2015-08-03 15:00 UTC
the complete error message is: `PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1009018979 bytes) in /$FOO/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 144
2`

the relevant code is:

```
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$conn = new AMQPStreamConnection($FOO, $FOO, '$FOO, $FOO '/', false, 'AMQPLAIN', null, 'en_US', 3, 3, null, FALSE, 30);

$chan = $conn->channel();

$chan->exchange_declare(EXCHANGE, 'topic', TRUE);

$chan->queue_declare(QUEUE);

$chan->queue_bind(QUEUE, EXCHANGE, ROUTING_KEY);

$chan->basic_consume(QUEUE, $consumer, false, false, false, false, 'processMessage');

register_shutdown_function('shutdown', $chan, $conn);

declare(ticks = 1);

pcntl_signal(SIGTERM, "sig_handler");

function sig_handler($signo){
    global $chan, $conn;

    switch($signo){
        case SIGTERM:
            shutdown($chan, $conn);
            break;
        default:
            break;
    }
}

function shutdown($chan, $conn){
    $chan->close();

    $conn->close();
}

while(count($chan->callbacks)){
    try{
        $chan->wait();
    }
    catch(PhpAmqpLib\Exception\AMQPTimeoutException $e){
    }
}

function processMessage($msg){
// do stuff
}



```

**Comment by sylvainbannier** [comment] 2015-09-08 13:55
Same issue here on php 5.3.3 with `php-amqplib` 2.4.1, 2.5.1 and 2.5.2.
testing code from http://www.rabbitmq.com/tutorials/tutorial-one-php.html

**Comment by nubeiro** [comment] 2016-02-15 08:05
@postalservice14 please take a look, I'd say we can close this one.

**Comment by postalservice14** [comment] 2016-02-15 21:09
@paericksen can you confirm you are on a pre RabbitMQ 1.8 release?

If so, I agree, that we shouldn't focus on that old of a version.

**Comment by paericksen** [comment] 2016-02-15 21:12
I'm using RabbitMQ 3.5.3, Erlang R14B04

**Comment by lukebakken** [comment] 2018-01-16 23:39
Closing due to inactivity. If this issue can be reproduced using the latest version of this library (`2.7.0`), RabbitMQ and a recent Erlang (`19.3` or later), please re-open it and indicate so. Thanks!

**Closed by lukebakken** 2018-01-16 23:39 UTC
Labels: wontfix
