### ISSUE TITLE
infinite loop inside StreamIO::write, in case of broken connection

### ISSUE THREAD

**Issue by programmer512** [php-amqplib/php-amqplib#624] opened 2018-11-19 16:30 UTC
OS: Ubuntu 14.04.2 LTS
Kernel verion: 3.16.0-30-generic
php version:: PHP 7.1.12-3+ubuntu14.04.1+deb.sury.org+1 (cli)
php-amqplib version: 2.8.1

https://github.com/php-amqplib/php-amqplib/blob/4664f9fd2868a1130998a9dc79afd7b1f70968a8/PhpAmqpLib/Wire/IO/StreamIO.php#L311

i had a situation when connection to rabbit is broken (due to broken VPN connection) and we do "AMQPChannel::basic_publish".
i noticed an infinite loop inside StreamIO::write. 
` $buffer = fwrite($this->sock, mb_substr($data, $written, 8192, 'ASCII'), 8192);`

$buffer is equal to 0 ($buffer === 0, but feof($this->sock) is equal to false. And as a result we have this endless loop. Exception AMQPConnectionClosedException is never thrown and $written variable stay as it is  `"$written += 0`"

Best Regards,

**Comment by lukebakken** [comment] 2018-11-19 16:38
Can you reproduce this easily?

**Comment by programmer512** [comment] 2018-11-19 17:10
@lukebakken yes. in order to reproduce this we need to use vpn  to connect over it to rabbitmq server  and create such script:
` $connection = new \PhpAmqpLib\Connection\AMQPConnection( 'xx.xx.xx.xx', '5672', 'test','test', '/', false, "AMQPLAIN", null,"en_US", 3.0,3.0, null,false,0);
        $channel = $connection->channel();
        sleep(10); //during this period we can drop a connection (drop vpn connection)
       for ($i=0;$i<1000;$i++) {
                $channel->basic_publish(new \PhpAmqpLib\Message\AMQPMessage('test'), 'xxxxx', 'xxxxx');
       }
`

**Comment by lukebakken** [comment] 2018-11-19 17:12
Thank you, that helps a lot. I can simulate the dropped connection with toxiproxy.

**Comment by programmer512** [comment] 2018-11-19 20:39
as i can see` feof($this->sock)`  it was added here:
https://github.com/php-amqplib/php-amqplib/commit/2e9805d258db30ebef984acfdf2e06a32c06ac04#r31356105

and i wonder why we need it here? what it be if we just check for `$buffer === 0 `?

**Comment by lukebakken** [comment] 2018-11-19 22:02
@programmer512 - the fix for this issue will probably be like [this code](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L250-L262).

@roihq - could you please address [this comment](https://github.com/php-amqplib/php-amqplib/commit/2e9805d258db30ebef984acfdf2e06a32c06ac04#r31356105) about `feof`? Thanks.

**Comment by programmer512** [comment] 2018-11-20 08:22
i suggest to change logic to the following:
if fwrite returns 0 bytes which were written, we will try to write it one more time but only during "read_write_timeout", not endlessly.  i believe fwrite can returns 0 bytes if its buffer is overflowed.
And suggest to remove   foef

**Comment by lukebakken** [comment] 2019-02-18 20:23
@programarivm would you mind confirming that this is fixed by #642? Thank you.

**Comment by ramunasd** [comment] 2019-02-19 07:54
Here is a good comment about confusing fwrite behaviour:
http://php.net/manual/en/function.fwrite.php#96951

So here we should throw connection exception whenever fwrite failed to write all bytes.
I can check this.

**Comment by lukebakken** [comment] 2019-02-19 14:24
@ramunasd - thanks I appreciate it. There should be several re-tries if `0` is returned from `fwrite`.

**Comment by programmer512** [comment] 2019-02-25 10:37
@lukebakken , yes we need to do several re-tries if 0, and  after that only (during some period of time) throw exception. 
Also question is still open why we have this check  feof($this->sock)

**Comment by programmer512** [comment] 2019-02-25 10:50
> @programarivm would you mind confirming that this is fixed by #642? Thank you.

this is another issue, related to writing to sockets, not reading

**Comment by ramunasd** [comment] 2019-02-25 11:35
@programmer512 IMHO fwrite() behaviour with broken connections depends on whether socket is blocking or not.
On blocking sockets You will get zero whenever server is not ready accept more data or connection is broken. One way to detect broken connections is feof().
On non blocking sockets You won't get zero as result of fwrite(), because data will be buffered in memory and only consuequent fread() will throw error - tested with toxiproxy. Unless You are writing more than buffer can accept, then fwrite() might trigger error as well.

So which case is Yours? :)

**Comment by programmer512** [comment] 2019-02-26 13:03
> @programmer512 IMHO fwrite() behaviour with broken connections depends on whether socket is blocking or not.
> On blocking sockets You will get zero whenever server is not ready accept more data or connection is broken. One way to detect broken connections is feof().
> On non blocking sockets You won't get zero as result of fwrite(), because data will be buffered in memory and only consuequent fread() will throw error - tested with toxiproxy. Unless You are writing more than buffer can accept, then fwrite() might trigger error as well.
> 
> So which case is Yours? :)
@ramunasd thank you for great explanation
I use non blocking sockets, phpamqplib switches it to be non blocking in case of handling pcntl signals in StreamIO::connect. So it could be issue( as i mentioned above) that  buffer is overflowed, and it cannot accept more bytes, because system cannot send it via network

**Comment by ramunasd** [comment] 2019-02-27 09:05
Another observation - on my testing machine I cannot disable or change stream write buffer here: https://github.com/php-amqplib/php-amqplib/blob/4664f9fd2868a1130998a9dc79afd7b1f70968a8/PhpAmqpLib/Wire/IO/StreamIO.php#L192

This function returns non zero value therefore it means buffer is enabled and it's size depends on OS.

Very likely fwrite() is triggering warning with error SOCKET_EAGAIN or SOCKET_EWOULDBLOCK which gets silenced in error handler function.

I wonder whether stream_select() could help here? Hovewer we need to add write timeout check here.

**Comment by ramunasd** [comment] 2019-02-27 09:46
@programmer512 Maybe somehow You could test broken connection with this verbose tool?
https://gist.github.com/ramunasd/531214db3420ca8f95cb0fe0f3e5de21

Just to prove that my suspicions are correct. Thanks in advance.

**Comment by programmer512** [comment] 2019-02-27 14:46
@ramunasd thank you

i will check this:

Very likely fwrite() is triggering warning with error SOCKET_EAGAIN or SOCKET_EWOULDBLOCK which gets silenced in error handler function.

**Comment by programmer512** [comment] 2019-02-27 15:17
@ramunasd , you are definitely  right , it always got silented because of custom error handler:
I endlessly   receive an error:
"fwrite(): send of 32 bytes failed with errno=11 Resource temporarily unavailable"

and this lines makes it silent:

  if (strpos($errstr, self::$ERRNO_EQUALS_EAGAIN) !== false || strpos($errstr, self::$ERRNO_EQUALS_EWOULDBLOCK) !== false) {
            return null;
        }

**Comment by programmer512** [comment] 2019-02-27 15:22
@ramunasd 
stream_set_write_buffer returns "-1" for me

**Comment by ramunasd** [comment] 2019-02-27 17:34
thanks @programmer512, fix almost ready for PR

**Comment by lukebakken** [comment] 2019-03-08 20:13
Fixed by #653

**Closed by lukebakken** 2019-03-08 20:13 UTC
