### ISSUE TITLE
Connection recovery

### ISSUE THREAD

**Issue by enleur** [php-amqplib/php-amqplib#367] opened 2016-02-12 07:13 UTC
In Java/C# drivers they have automatic connection recovery:
https://www.rabbitmq.com/api-guide.html#recovery

It would be great to have the same in this lib. In our production we suffer from "Broken pipe or closed connection" or "Expected 7 bytes but got 0" exceptions. I'm not sure where it exactly happens, it's hard to reproduce on the local environment but here are some possible cases:
- Lost network connection between servers
- Rabbitmq server can't handle connections and drops it
- Processing a message takes a long time and a socket resets
- The heartbeat tries to send a frame message, but fails

Some related issues:
https://github.com/php-amqplib/php-amqplib/issues/353
https://github.com/php-amqplib/RabbitMqBundle/issues/301

I guess this issue duplicates https://github.com/php-amqplib/php-amqplib/issues/68

**Comment by michaelklishin** [comment] 2016-02-12 12:11
Java and .NET use long-lived connections. From what I see reported on the list, PHP is often nearly the opposite of that, so connection recovery is of limited use.

On top of that, as Bunny suggests, connection recovery in a single-threaded environment is not impossible but it's easier to simply throw and exception and expect app developers to handle it. In Bunny, Java, and .NET clients recovery is kicked off by a thread that handles network I/O.

**Comment by lukebakken** [comment] 2018-01-16 23:29
Closing, duplicate of #68

**Closed by lukebakken** 2018-01-16 23:29 UTC
Labels: feature
