### ISSUE TITLE
Exception when running demo

### ISSUE THREAD

**Issue by orensol** [php-amqplib/php-amqplib#55] opened 2013-01-01 11:13 UTC
oren@oren-laptop:~/vendor/videlalvaro/php-amqplib/demo$ php amqp_consumer.php 
< [hex]:
0000  41 4D 51 50 01 01 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
> 10,10: Connection.start
Start from server, version: 8.0, properties: capabilities=(), copyright=Copyright (C) 2007-2012 VMware, Inc., information=Licensed under the MPL.  See http://www.rabbitmq.com/, platform=Erlang/OTP, product=RabbitMQ, version=2.8.7, mechanisms: PLAIN, AMQPLAIN, locales: en_US
< [hex]:
0000  01 00 00 00 00 00 A2 00  0A 00 0B 00 00 00 38 07   ......�. ......8.
0010  6C 69 62 72 61 72 79 53  00 00 00 13 50 48 50 20   libraryS ....PHP 
0020  53 69 6D 70 6C 65 20 41  4D 51 50 20 6C 69 62 0F   Simple A MQP lib.
0030  6C 69 62 72 61 72 79 5F  76 65 72 73 69 6F 6E 53   library_ versionS
0040  00 00 00 03 30 2E 31 08  41 4D 51 50 4C 41 49 4E   ....0.1. AMQPLAIN
0050  00 00 00 4F 05 4C 4F 47  49 4E 53 00 00 00 16 61   ...O.LOG INS....a
0060  70 70 31 30 35 35 30 30  35 31 5F 68 65 72 6F 6B   pp105500 51_herok
0070  75 2E 63 6F 6D 08 50 41  53 53 57 4F 52 44 53 00   u.com.PA SSWORDS.
0080  00 00 20 74 66 38 47 41  4E 51 46 76 36 4D 6B 39   .. tf8GA NQFv6Mk9
0090  63 33 32 72 4D 5A 56 6A  6E 75 35 35 5F 48 55 36   c32rMZVj nu55_HU6
00A0  33 42 56 05 65 6E 5F 55  53 CE                     3BV.en_U S

< 10,11: Connection.start_ok
waiting for 10,20, 10,30
waiting for a new frame
> 10,30: Connection.tune
< [hex]:
0000  01 00 00 00 00 00 0C 00  0A 00 1F FF FF 00 02 00   ........ ...��...
0010  00 00 00 CE                                        ...

< 10,31: Connection.tune_ok
< [hex]:
0000  01 00 00 00 00 00 1E 00  0A 00 28 17 2F 61 70 70   ........ ..(./app
0010  31 30 35 35 30 30 35 31  5F 68 65 72 6F 6B 75 2E   10550051 _heroku.
0020  63 6F 6D 00 00 CE                                  com..

< 10,40: Connection.open
waiting for 10,41, 10,50
waiting for a new frame
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error reading data. Received 0 instead of expected 1 bytes' in /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:61
Stack trace:
#0 /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(94): PhpAmqpLib\Wire\AMQPReader->rawread(1)
#1 /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(268): PhpAmqpLib\Wire\AMQPReader->read_octet()
#2 /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(288): PhpAmqpLib\Connection\AMQPConnection->wait_frame()
#3 /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(143): PhpAmqpLib\Connection\AMQPConnection->wait_channel(0)
#4 /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(240): PhpAmqpLib\Channel\AbstractChannel->next_frame()
#5 /home/oren/workspac in /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 61

**Comment by nubeiro** [comment] 2016-02-21 17:57
I can't reproduce it either, using RabbitMQ 3.6.0 and latest master branch. 
Since the issue is more than 2 years old I'll just close it.

**Closed by nubeiro** 2016-02-21 17:57 UTC
Labels: discussion
