### ISSUE TITLE
Notices in PhpAmqpLib/Wire/IO/StreamIO.php during failed fwrite

### ISSUE THREAD

**Issue by andygrunwald** [php-amqplib/php-amqplib#91] opened 2013-08-15 17:21 UTC
Hey,

my PHP error log mentioned some notices in a PHP 5.5.1 environment on Ubuntu 12.04:

```
[15-Aug-2013 09:13:49 Europe/Berlin] PHP Notice:  fwrite(): send of 12 bytes failed with errno=104 Connection reset by peer in /var/application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 61
[15-Aug-2013 09:13:49 Europe/Berlin] PHP Notice:  fwrite(): send of 19 bytes failed with errno=32 Broken pipe in /var/application/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 61
```

This are only notices and all seems to be working as normal, but i think this has to be fixed. At the moment i do not know any kind of fix for this.
Maybe you got an idea.

**Comment by thibaut1001** [comment] 2015-01-21 15:20
i have the same problem? what could i do for solve this?

**Comment by marlene16** [comment] 2015-04-06 09:27
I also have the same problem.. From time to time, I got this message. Does anyone solve this problem?

**Comment by michaelklishin** [comment] 2015-04-06 12:40
```
fwrite(): send of 12 bytes failed with errno=104 Connection reset by peer
```

This is a pretty clear indication that RabbitMQ (or a firewall/proxy/etc in between) has closed TCP connection. See RabbitMQ logs to find out what may be the reason but failed writes can happen due to intermittent connectivity issues. I don't think silencing such warnings is a good idea.

**Comment by marlene16** [comment] 2015-04-07 08:38
Thanks for the response, I'll try to find out what cause the problem.

**Comment by marwan2** [comment] 2015-04-15 14:48
fwrite(): send of 12 bytes failed with errno=104 Connection reset by peer

I have the same error also, the application was working properly but suddenly, we got this message!!!

**Comment by skolodyazhnyy** [comment] 2015-06-29 14:59
Any update on this? It happens to me as well, I'm getting error every time after 5th message,

```
[PhpAmqpLib\Exception\AMQPRuntimeException] Broken pipe or closed connection
```

RabbitMQ logs says,

```
=INFO REPORT==== 29-Jun-2015::14:57:50 ===
accepting AMQP connection <0.694.0> (172.17.0.119:58150 -> 172.17.0.118:5672)

=ERROR REPORT==== 29-Jun-2015::14:57:50 ===
Error on AMQP connection <0.694.0> (172.17.0.119:58150 -> 172.17.0.118:5672, vhost: '/', user: 'guest', state: running), channel 1:
{amqp_error,unexpected_frame,
            "expected method frame, got non method frame instead",none}
```

May be related with #256.

**Comment by seaneble** [comment] 2016-03-15 15:14
I daemonized php-amqplib with PHP 7 using `basic_get`. Unfortunately, the error message is more drastic in that setup:

    PHP Fatal error:  Uncaught ErrorException: fwrite(): send of 49 bytes failed with errno=104 Connection reset by peer in /…/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:271

I would like to be able to handle this error with a try/catch block to throw a nice error to my console or try to reconnect after a while. Currently, I use a custom shutdown function, but that is not a very pretty solution.

I'm not sure how exactly this is related to the other user's problems, but I thought I might try this issue before opening another.

Sebastian

**Comment by rozehnal** [comment] 2016-04-22 07:49
Hi, we have the same problem on RabbitMQ 3.6.1. The worker fails randomly after couple messages - sometimes it can handle couple hundreds sometimes less then 10. I'm able to replicate the bug so if I anybody has any idea we can easily validate it.

We use current version of php-amqplib.

trace log:
```
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com gateway-jobs[18380]: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'fwrite(): send of 21 bytes failed with errno=104 Connection reset by peer' in /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:271
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com Stack trace:
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/home/gateway/v...', 271, Array)
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #1 /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(271): fwrite(Resource id #169, '????????<?P????...', 8192)
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #2 /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('????????<?P????...')
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #3 /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(448): PhpAmqpLib\Connection\AbstractConnection->write('????????<?P????...')
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #4 /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(226): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
2016-04-21T10:16:43+01:00 cron600.job.core.test06.l01.dsg-i.com #5 /h in /home/gateway/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 271
```

Thanks,
Pavel

**Comment by rozehnal** [comment] 2016-04-26 10:44
Hi, in our case helped specification of quality of service - https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.qos.prefetch-count - prefetch-count parameter to a small value.

**Comment by mshauneu** [comment] 2016-07-01 16:19
@rozehnal could you please explain in more details?

**Comment by basert** [comment] 2016-07-02 16:11
@mshauneu You can set the QoS (prefetch count) of a consumer in his channel.
```php
$connection = new AMQPStreamConnection($args...);
$channel = $connection->channel();
$channel->basic_qos(0, <PREFET_COUNT>, false);
```

**Comment by mshauneu** [comment] 2016-07-02 18:35
thank you @basert

**Comment by weburnit** [comment] 2016-08-23 13:36
I guess the problem might come from your queue settings(fetch count) and number of message you fetch are not them same value.

**Comment by pvgomes** [comment] 2016-10-14 20:28
I first and more important think that we need to do in this case is try to "print" you content message and only return true to consumer, don't process your real code, if you can "consume" the messages the problem its not in rabbit but in our process because probably we expend to much time to acknowledge message to rabbit and Rabbit close connections.

In my case I change the approach the problem its because I have many product ids for each message and its expend long time to ACK process so I fit my messages and it work well after do that.

We can change the approachs like create another queues to fit this messages, I don't know, but 90% of problems it is.

Look that here [Detecting Dead TCP Connections with Heartbeats and see more](https://www.rabbitmq.com/heartbeats.html)

**Comment by tiborb** [comment] 2016-12-16 15:01
I had the same issue that the consumer exited with "fwrite(): send of 21 bytes failed with errno=104 Connection reset by peer" after processing ~2k messages in a very short time. Than I set the prefetch count = 1 and it got stable. It migt cost some performance but that is not very critical.

**Comment by GeoffreyHervet** [comment] 2017-02-14 11:46
+1

**Comment by arunappulal** [comment] 2017-02-23 06:08
+1

**Comment by mihailShumilov** [comment] 2017-03-10 13:06
+1


Exception 'ErrorException' with message 'fwrite(): send of 19 bytes failed with errno=32 Broken pipe'

in /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:281

Stack trace:
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/Users/godson/S...', 281, Array)
#1 /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(281): fwrite(Resource id #78, '\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...', 8192)
#2 /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#3 /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(448): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#4 /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(230): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#5 /Users/godson/Sites/timeshare.loc/core/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(167): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#6 /Users/godson/Sites/timeshare.loc/core/common/components/RabbitMQComponent.php(68): PhpAmqpLib\Channel\AMQPChannel->close()

**Comment by sjoerdmaessen** [comment] 2017-04-15 05:58
+1

**Comment by kustov-vitalik** [comment] 2017-04-19 12:00
+1

**Comment by mstrouhal** [comment] 2017-05-09 19:20
+1

**Comment by michaelklishin** [comment] 2017-05-09 19:39
I'm not sure how this client can "fix" a message that says that a socket write failed because TCP connection was closed by peer (or any other reason). Such errors can be handled

In most client libraries I can think of (not just for RabbitMQ) socket write failures are usually logged one way or another.

Sorry to rain on the parade of +1s but unless there is a specific proposal as to how socket write failures can be handled differently (and how that'd be an improvement), there is no reason why this should remain open.

**Closed by michaelklishin** 2017-05-09 19:39 UTC
Labels: watchlist

**Comment by speller** [comment] 2017-09-26 03:55
@michaelklishin It will be nice to provide any useful instruction what to check to fix this issue. It is very easy to say 'this is not our problem', but it will not help

**Comment by michaelklishin** [comment] 2017-09-26 04:58
@speller please take some time to understand what a failed socket write might mean. #424 covers some of them. Like I said there and in other issues, some of them are NOT under this client's control and cannot be considered this client's issues.

**Comment by michaelklishin** [comment] 2017-09-26 05:01
I'm locking this issue as we need specific scenarios in which failed socket writes can be handled better, not a parade of +1s, "please suggest what can I do to make this stack trace go away" kind of comments. If you have specific observations on when this happens, including server logs, please file new issues and provide more information. That's what contributors and maintainers need to make the client better, not a dozen of other +1s.

**Comment by michaelklishin** [comment] 2017-09-26 05:40
@speller I have provided a brief Q&A on [what can cause socket write failures and how to narrow down the root cause by looking at RabbitMQ log entries](https://github.com/php-amqplib/php-amqplib/issues/424#issuecomment-332090471).
