### ISSUE TITLE
fwrite(): send of 3728 bytes failed with errno=11 Resource temporarily unavailable

### ISSUE THREAD

**Issue by rik-coenders** [php-amqplib/php-amqplib#613] opened 2018-10-30 16:01 UTC
Since version 2.8.0 I get the exception

```
/data/www/web03.adchieve.com/releases/133/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php - 301 - fwrite(): send of 3728 bytes failed with errno=11 Resource temporarily unavailable
```

I did not have issues in the previous version.

I use the AMQPStreamConnection and pcntl is installed.

**Comment by lukebakken** [comment] 2018-10-30 16:18
Is this consistent? There is a chance that this is related to #612 - is there a way for you to test using the fix in that pull request?

**Comment by rik-coenders** [comment] 2018-10-30 16:22
I did notice the duplicate restoring error handler, but if I read the code correctly, it does not explain the problem (since the error handler is registered again every time).

I tried to reproduce the problem. It is a persistent issue on our live environment (so we decided to downgrade to 2.7.3 for that). On my development environment I cannot reproduce the issue.

**Comment by lukebakken** [comment] 2018-10-30 16:40
@rik-coenders - I merged #612. Please give [`v2.8.1-rc1`](https://github.com/php-amqplib/php-amqplib/releases/tag/v2.8.1-rc1) a try if possible.

**Comment by NGTOne** [comment] 2018-10-30 17:28
Also seeing this since 2.8.0, and with 2.8.1-rc1 as well.

Seems to crop up for me with larger message volumes (>100) sent over a single connection.

**Comment by lukebakken** [comment] 2018-10-30 17:50
@rik-coenders @NGTOne since I can't reproduce this please take a look at the following diff to see if something stands out: [link](https://github.com/php-amqplib/php-amqplib/compare/v2.7.3...v2.8.1-rc1)

**Comment by rik-coenders** [comment] 2018-10-30 18:08
I already did look at the diff but I did not see anything extraordinary.

I expect that the error handler is executed because the error is thrown from StreamIO line 301 (in version 2.8.0), which means an ErrorException is thrown somewhere, and the only place that could throw it is the error handler in the class.

I will try to send many large messages in my development environment to see if I can reproduce the issue.

**Comment by rik-coenders** [comment] 2018-10-30 18:39
Finally managed to find the issue.

The error handler is called with errno `8` and errstr `fwrite(): send of 2948 bytes failed with errno=11 Resource temporarily unavailable`. The constants SOCKET_EAGAIN and SOCKET_EWOULDBLOCK are both equal to `11`. The `8` is coming from the constant E_NOTICE.

Comparing them obviously fails, so a EAGAIN is not handled correctly.

**Comment by lukebakken** [comment] 2018-10-30 18:50
Great find @rik-coenders ... that must be why the string comparison existed (which of course doesn't work in non-English environments).

I will see if there's a way to get the "real" `errno` without parsing the string for `errno=N`. If this is a scenario you are familiar with, by all means chime in.

**Comment by rik-coenders** [comment] 2018-10-30 18:56
A quick google search gave me no results other than parsing the string, unfortunately.

**Comment by lukebakken** [comment] 2018-10-30 19:10
@rik-coenders would it be convenient for you to test #614 or should I create `v2.8.1-rc2` ? Thanks again.

**Comment by rik-coenders** [comment] 2018-10-31 08:19
I have tested it and it does not work for me. `socket_last_error` returns `null`.

The documentation of http://php.net/manual/en/function.socket-last-error.php says the socket should be a socket opened with socket_create, so I think it does not work with a stream socket (which is a stream, not a socket).

**Comment by davidgreisler** [comment] 2018-10-31 11:06
We solved this by checking for `errno` in the string with `if (strpos($errstr, 'errno=11') !== false) {`. Wouldn't this work even with translated strings, or do they also translate `errno`?

**Comment by rik-coenders** [comment] 2018-10-31 12:15
@davidgreisler I don't know about the translated strings, but the solution you suggest should at least read the errno from the constant. Running in docker gives me `SOCKET_EAGAIN = 11`, but on my mac, `SOCKET_EAGAIN = 35`

**Comment by davidgreisler** [comment] 2018-10-31 13:53
I created PR #615 containing our fix for the problem. With the changes we made it works for us now. Maybe someone who uses another language (with translated error messages) can also test the change?

**Comment by lukebakken** [comment] 2018-10-31 15:00
Thanks. I expected this discussion to be on PR #614. I will re-open #615.

**Comment by lukebakken** [comment] 2018-10-31 15:13
@rik-coenders thanks a lot for testing #614.

**Comment by lukebakken** [comment] 2018-11-02 23:08
@davidgreisler @NGTOne @rik-coenders please give `2.8.1-rc2` a try -

https://github.com/php-amqplib/php-amqplib/releases/tag/v2.8.1-rc2

**Closed by lukebakken** 2018-11-02 23:08 UTC
Labels: bug

**Comment by lukebakken** [comment] 2018-11-07 17:15
@davidgreisler @NGTOne @rik-coenders I have tagged [`v2.8.1-rc3`](https://github.com/php-amqplib/php-amqplib/releases/tag/v2.8.1-rc3). If you have a second to test, that would be great. Thanks!

**Comment by davidgreisler** [comment] 2018-11-08 14:57
We are using `v2.8.1-rc2` since a few days now and it's working fine for us. :+1:

**Comment by clozed2u** [comment] 2018-11-12 16:36
Same problem here. Just tested [`v2.8.1-rc3`](https://github.com/php-amqplib/php-amqplib/releases/tag/v2.8.1-rc3) and it's work fine for me.

**Comment by gitkv** [comment] 2019-04-24 18:16
On version 2.8.1-rc3 and above, everything works well, there are no problems.
