### ISSUE TITLE
Endless loop after broken connection with rabbitmq in AMQPReader::rawread because of zero timeout

### ISSUE THREAD

**Issue by programmer512** [php-amqplib/php-amqplib#622] opened 2018-11-16 12:22 UTC
OS: Ubuntu 14.04.2 LTS
Kernel verion: 3.16.0-30-generic
php version:: PHP 7.1.12-3+ubuntu14.04.1+deb.sury.org+1 (cli) 
php-amqplib version: 2.8.1

we use VPN  connection in order to connect to our rabbitmq server. 
lets consider an example of code:

       $connection = new \PhpAmqpLib\Connection\AMQPConnection('xx.xx.xx.xx', '5672','test','test', 
        '/',false,"AMQPLAIN", null,"en_US",3.0,3.0,null,false,0);

        sleep(10);  //during this time we can drop a connection to rabbitmq (stop vpn connection)

        $connection->channel()->basic_consume('amq.rabbitmq.reply-to', '', false, true, false, false, function (\PhpAmqpLib\Message\AMQPMessage $message) {});

i can see that this script never stopped, because it hangs inside the loop in AMQPReader::rawread:

           protected function rawread($n)
            {
             ......
                    while (true) {
                        $this->wait();
                        try {
                            $res = $this->io->read($n);
                            break;
                        } catch (AMQPTimeoutException $e) {
                            if ($this->getTimeout() > 0) {
                                throw $e;
                            }
                        }
                    }
                    $this->offset += $n;
                    return $res;
                
                ......
            }
`

this is because $this->getTimeout()  equal to zero and AMQPTimeoutException is not thrown to the upper level in this case.
**fwrite** are not fail in this case and successfully write bytes to such socket. 
 **fread** inside **StreamIO::read($len)** always returns an empty string "" for such broken socket

This happens when we are waiting for a response from rabbitmq, in my concrete situations we are waiting for "basic.consume_ok". But this situation can be happened to any other types of commands when we need to wait a response from rabbitmq and we do not have a timeouts for them

Thanks in advance.

**Comment by programmer512** [comment] 2018-11-16 13:43
Of course enabling heartbeats will solve this issue, script stopped with AMQPHeartbeatMissedException(  "Missed server heartbeat"), but i meant exactly the case when  heartbeats are disabled.

**Comment by lukebakken** [comment] 2018-11-17 13:41
This code *should* detect too many empty reads:

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L250-L262

You are using `false` for `$nowait`, which means this `wait()` call on the channel won't pass a timeout:

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L952-L954

I should probably change the channel `wait()` function to default to the `read_write_timout` value.

**Comment by lukebakken** [comment] 2018-11-17 13:42
A workaround would be to pass `true` to `$nowait` and wait on the channel yourself, passing a `timeout` argument.

**Comment by programmer512** [comment] 2018-11-17 22:52
@lukebakken , thank you for your answer.
Yes, it will be  brilliant having a default timeout for waiting responses from server for all commands.
I know about $nowait option, but for example for basic_get and other methods we do not have such option and this problem can occurred there as well. 
About heartbeats yes, they can solve this issue.  But using heartbeats is not always comfortable, because we need constantly send heartbeats from client to server in other case (2 missed heartbeats) server will close connection, but our script can be late for sending such heartbeats because it can be busy doing another it's tasks.
In my personal opinion it will be very good to always have a default timeout for read response operations it order not to hang up

**Comment by programmer512** [comment] 2018-11-19 21:59
This issue also could happen even during __destruct mechanism because it does closing connection and closing channels. Сlosing channels waiting for response from rabbit "channel.close_ok" and can wait infinite time because does not have timeout as well

**Comment by lukebakken** [comment] 2018-11-19 22:01
@programmer512 I'd be happy to review a pull request.

**Comment by ramunasd** [comment] 2019-01-16 12:19
@lukebakken this one is quite clear. When timeout=0, AMQPReader->rawread() supress AMQPTimeoutException thrown in StreamIO->read() and starts everything again. So yes, it's infinite loop and serious bug.

I would suggest to throw AMQPIOWaitException or AMQPDataReadException, because AMQPTimeoutException mostly means expired wait time rather than connection problems.

**Comment by lukebakken** [comment] 2019-01-16 14:49
I'm happy to review pull requests. I have no time to work on this library at the moment.

**Comment by ramunasd** [comment] 2019-01-25 07:31
Hi @programmer512 , there is fix for that at https://github.com/ramunasd/php-amqplib/commit/242db8072cb46f3da79e76300140a6e152d04d37
Can You try it and tell how it goes?

**Comment by programmer512** [comment] 2019-01-26 18:47
@ramunasd , thank you very much.
Will check it and get back to you

**Comment by programmer512** [comment] 2019-02-13 17:36
@ramunasd . i tried and it works fine for me - no endless loop anymore, seems fine
thank you

**Comment by lukebakken** [comment] 2019-02-18 20:08
@programarivm confirmed this is fixed by #642

**Closed by lukebakken** 2019-02-18 20:08 UTC
Labels: bug
