### ISSUE TITLE
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException

### ISSUE THREAD

**Issue by glo71317** [php-amqplib/php-amqplib#1153] opened 2024-01-20 12:34 UTC
**Version(s) affected**: 3.6.0

**Description**  
After updating the latest version of "php-amqplib/php-amqplib":"^3.6.0", we getting below error.
<img width="576" alt="Screenshot 2024-01-20 at 6 01 06 PM" src="https://github.com/php-amqplib/php-amqplib/assets/85922880/aca6a96a-84d9-4fe3-a0f3-6a8b1a18c6e4">
when are using 3.5.4 and other previous versions, we did not find any issue.

Might be some issue introduced in new version 3.6.0

**How to reproduce**  
In adobe commerce when we update this library with latest version we started getting `PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException` If need the sample code to reproduce this with sample code then we have to work on.

I think some backward compatibility issue which is introduced in patch version 3.6.0 because 3.5.4 is working fine for us.
if you needed anything from our end we will try to provide.

**Possible Solution**  

**Additional context**  
<img width="576" alt="Screenshot 2024-01-20 at 6 01 06 PM" src="https://github.com/php-amqplib/php-amqplib/assets/85922880/5f90124a-f359-4509-acd8-39950ebba352">

**Comment by ramunasd** [comment] 2024-01-20 16:15
Error message clearly says "**no exchange 'magento' in vhost"**. Looks like You are trying to bind queue to non existing exchange and it's not a library issue.

**Comment by lukebakken** [comment] 2024-01-20 17:56
Thank you @ramunasd

**Comment by glo71317** [comment] 2024-01-22 13:25
> Error message clearly says "**no exchange 'magento' in vhost"**. Looks like You are trying to bind queue to non existing exchange and it's not a library issue.

We are not having any code change in adobe commerce for rabbitmq, but unfortunate after upgrade latest version 3.6.0 from 3.5.4.
<img width="855" alt="Screenshot 2024-01-22 at 6 52 27 PM" src="https://github.com/php-amqplib/php-amqplib/assets/85922880/e9ccf9bb-ed4c-4ebb-a360-91277fa3be80">

There is no issue with 3.5.4, it seems some breaking changes are introduced in latest version 3.6.0 which should not happened in minor version.

**Comment by lukebakken** [comment] 2024-01-22 17:19
@glo71317 you will have to provide a way for us to reproduce this error.

In addition, your second screenshot is a _DIFFERENT-_ exception than what you posted before, and suggests your application can't connect to RabbitMQ.

We can't assist you with inconsistent, incomplete information, and we do not have the time to guess how to reproduce your issue, especially since we're giving you _free_ support.

At the very least, you should be able to provide code that demonstrates this issue.

**Comment by glo71317** [comment] 2024-01-23 11:26
@lukebakken thank you for the response!
Regarding first screenshot it was my mistake, i attached some different screenshot. sorry for the same.
Second screenshot is correct, RabbitMQ connection is not happening due to the change - https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Connection/AMQPStreamConnection.php#L48C67-L48C79
Here, no of argument checking 17 which can accept the class - AMQPStreamConnection but now there is restricted by 17 along with ssl_protocol condition.

According recent code, both the condition should be false then connection will happen.

In order to provide the sample code demonstrates this issue we have to work on then we can give, 
Quick details from Adobe commerce
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Amqp/Connection/Factory.php#L26-L43
When create a object of AMQPStreamConnection by ObjectManager then its picking all the arguments.

So, it seems to me we have to make a change in adobe commerce side if your side there is no issue. but that is sure backward compatibility issues are introduced in recent version 3.6.0 which should not happened in minor version.

All types of consumers are affecting either paid or free.

**Comment by lukebakken** [comment] 2024-01-23 15:49
@glo71317 -

@ramunasd made a comment [here](https://github.com/php-amqplib/php-amqplib/pull/1116#issuecomment-1729734534) about the changed behavior.

@ramunasd do you have anything to add here?

@glo71317 I suggest opening a PR in the [Magento project](https://github.com/magento/magento2) to fix their use of this library.

**Comment by ramunasd** [comment] 2024-01-23 16:59
This can be considered as breaking change in some circustances, I must admit. Anyways, either with minor or major version, everyone will need to adapt someday. We can release tons of major versions and nobody won't complain. All those wrappers can stay with old versions and old bugs.

@egorgrushko, any suggestions how to deal with this situation?

**Comment by egorgrushko** [comment] 2024-01-23 17:31
@ramunasd, sorry, I'm not sure that I understand the problem yet. I see that ObjectManager should only pass 5 arguments. Or does it take some additional arguments from a configuration? How does this cause the connection to not occur?

**Comment by ramunasd** [comment] 2024-01-24 08:24
if secure connection enabled - then 6 arguments. And last one is ignored since version 3.6.0 @egorgrushko

**Comment by egorgrushko** [comment] 2024-01-24 12:06
@ramunasd, if this last one argument passed by ObjectManager was named "ssl_protocol", then it would be ignored, but the argument named "ssl_options". I mean, we haven't made any changes to the way "ssl_options" parameter is handled. How "ssl_options" can be ignored?

**Comment by ramunasd** [comment] 2024-01-24 14:39
hmmm, then I don't get how changes in 3.6.0 can break something 🤷 

Do You have any logical explanation? @glo71317

**Comment by glo71317** [comment] 2024-01-25 09:42
@ramunasd @egorgrushko 
If you can see we are attempting to make connection https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Amqp/Connection/Factory.php#L26-L43 and this request processed by object manager and reading the constructor parameters here - https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Code/Reader/ClassReader.php#L32-L62
If you see, here we are prepared the arguments values using ReflectionClass based on mandatory and optional. default values are taking from library class, consumers can have all the right to overwrite all the arguments or by passing mandatory one. So, In our case out of 17 arguments only 4 are mandatory. Mandatory and few optional parameters we are passing during create a object from our end.

Only issue with condition `func_num_args() === 17 ` it seems it is not required and another condition
`$ssl_protocol !== null && $ssl_protocol instanceof AMQPConnectionConfig === false` it seems fine to me. By the first condition tight coupling happening.

Another work around, we have to fix at our end if you people will not do. Our only concern is breaking changes should be introduced in major version of library so someone want to update or use they can adapt Backward compatibility issue their side.

**Comment by ramunasd** [comment] 2024-01-25 11:04
> If you see, here we are prepared the arguments values using ReflectionClass based on mandatory and optional. default values are taking from library class. So number of arguments we are receiving 17 here - https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Connection/AMQPStreamConnection.php#L48C41-L48C53 and connection is failed due to this.

Still not clear why connection fails. If You pass 17 arguments, then deprecation warning is thrown. Is that problem? A new warning is not a breaking change, IMHO.

**Comment by glo71317** [comment] 2024-01-25 11:47
@ramunasd Still i am debugging and working to get the final root cause, one more thing i found 
this class is https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Connection/AMQPSSLConnection.php is extending to https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Connection/AMQPStreamConnection.php
and calling the parent class constructor.
Second last parameter is `ssl_protocol` in class `AMQPStreamConnection` but passing last parameter $config( It will be type of AMQPConnectionConfig or null). But based on sequence of parameters $config values assigned to `ssl_protocol`.

As far as we have the above findings, Still we are working on the RCA.

**Comment by glo71317** [comment] 2024-01-30 12:28
> @glo71317 we do have integration tests for secure connections
> 
> @egorgrushko any comments how to resolve this issue? maybe shall we revert changes if compatibility is broken?

I cannot see in any test uses of `AMQPSSLConnection` not sure that is working or not.

**Comment by egorgrushko** [comment] 2024-01-31 00:50
@ramunasd, of course we can revert the changes, but first we need to understand what the issue is so that it could be fixed in the next major release.
We need to understand the cause of this issue and how to fix it, either on the "client" side or on the php-amqplib side.

@glo71317 
> it is not validating properly here - https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Wire/IO/StreamIO.php#L428

What exactly not validating properly here?

> Hence throwing exception here - https://github.com/php-amqplib/php-amqplib/blob/v3.6.0/PhpAmqpLib/Wire/IO/StreamIO.php#L432

I don't see this exception in your stacktrace. There is nothing about "Can not enable crypto" in your stacktrace.

All I can say for now is that my organization uses ^3.6 in production without any issues, with self-hosted RabbitMQ, as well as with AmazonMQ, which has strict TLS requirements.

**Comment by glo71317** [comment] 2024-02-01 12:27
It is very hard to say there is client side or php-amqplib side. because i did not find correct RCA for the same.
<img width="677" alt="Screenshot 2024-02-01 at 5 53 56 PM" src="https://github.com/php-amqplib/php-amqplib/assets/85922880/3c22d914-543f-40d3-849d-1649abf460d2">

It is sure, issue with latest version of library but may be we have to adapt backward compatibility changes  but did not get what changes are required.

**Comment by egorgrushko** [comment] 2024-02-01 18:10
@glo71317 
You can try to create a docker image that can be used to reproduce the issue.
Without it, I don't think we can help you find the cause and fix it.

**Comment by ramunasd** [comment] 2024-02-06 19:55
I tested version 3.6.0 against local broker using self signed certificates and against CloudAMQP free instance with valid certificate. Both times everything worked fine if SSL options are correct.

@glo71317 from You we got 3 different exceptions in 3 different places, still no explanation how changes in 3.6.0 broke secure connection, no proposed way how to reproduce issue. I will close this issue within a week unless we get more info about it.

**Comment by ramunasd** [comment] 2024-02-12 19:01
We released version 3.6.1 which handle secure connection issues better. Can You test with that version? @glo71317

**Comment by glo71317** [comment] 2024-02-13 13:18
@ramunasd Will check and come back on this

**Comment by glo71317** [comment] 2024-03-07 13:17
@ramunasd Today i tested and found only one minor error which is coming from `trigger_error` method https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Connection/AMQPStreamConnection.php#L49

To fix this issue i raised one test pr - https://github.com/glo71317/php-amqplib/pull/1/files which worked well without any error.

Also, i read about https://www.php.net/manual/en/function.trigger-error.php, it shows `This function is useful when you need to generate a particular response to an exception at runtime.` 

it might also be fixed the issue if we call the method with sign @trigger_error. 

Please share your inputs and help us to move forward.

**Comment by ramunasd** [comment] 2024-03-07 15:54
We can use only native php functions. No plans for having symfony components as dependencies which does almost the same.

So we got confirmation that library works well and the issue can be closed.

@glo71317 please google how to change php error report level and disable deprecations if You cannot solve them.

**Closed by ramunasd** 2024-03-07 15:54 UTC
Labels: invalid

**Comment by glo71317** [comment] 2024-03-11 10:44
@ramunasd Are you planning to deliver this sooner - https://github.com/php-amqplib/php-amqplib/pull/1163/?
