### ISSUE TITLE
Recevived 0 instead of expected 7 bytes

### ISSUE THREAD

**Issue by jhonatanTeixeira** [php-amqplib/php-amqplib#481] opened 2017-04-27 01:29 UTC
```yml
old_sound_rabbit_mq:
    connections:
        default:
            host:     'amqp'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
            
            use_socket: true

consumers:
        save_person_notify:
            connection:       consume
            exchange_options: {name: 'save-notify', type: direct}
            queue_options:    {name: 'save-observer'}
            callback:         consumer.save_entity
            enable_logger:    true
```

when i run the consumer:
bin/console rabbitmq:consumer save_person_notify -vvv

i get this output:
```
[PhpAmqpLib\Exception\AMQPIOException]                      
  Error reading data. Received 0 instead of expected 7 bytes  
                                                              

Exception trace:
 () at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php:114
 PhpAmqpLib\Wire\IO\SocketIO->read() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:149
 PhpAmqpLib\Wire\AMQPReader->rawread() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:106
 PhpAmqpLib\Wire\AMQPReader->read() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:508
 PhpAmqpLib\Connection\AbstractConnection->wait_frame() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:555
 PhpAmqpLib\Connection\AbstractConnection->wait_channel() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:217
 PhpAmqpLib\Channel\AbstractChannel->next_frame() at /api/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:328
 PhpAmqpLib\Channel\AbstractChannel->wait() at /api/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php:54
 OldSound\RabbitMqBundle\RabbitMq\Consumer->consume() at /api/vendor/php-amqplib/rabbitmq-bundle/Command/BaseConsumerCommand.php:90
 OldSound\RabbitMqBundle\Command\BaseConsumerCommand->execute() at /api/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:848
 Symfony\Component\Console\Application->doRunCommand() at /api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:190
 Symfony\Component\Console\Application->doRun() at /api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /api/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /api/bin/console:27
```

Looking at the code bellow i think i may have found a problem.

AbstractConnection.php
```php
protected function wait_frame($timeout = 0)
    {
        if (is_null($this->input))
        {
            $this->setIsConnected(false);
            throw new AMQPRuntimeException('Broken pipe or closed connection');
        }

        $currentTimeout = $this->input->getTimeout();
        $this->input->setTimeout($timeout);

        try {
            // frame_type + channel_id + size
            $this->wait_frame_reader->reuse(
                $this->input->read(AMQPReader::OCTET + AMQPReader::SHORT + AMQPReader::LONG)
            );

            $frame_type = $this->wait_frame_reader->read_octet();
            $class = self::$PROTOCOL_CONSTANTS_CLASS;
            if (!array_key_exists($frame_type, $class::$FRAME_TYPES)) {
                throw new AMQPRuntimeException('Invalid frame type ' . $frame_type);
            }
            $channel = $this->wait_frame_reader->read_short();
            $size = $this->wait_frame_reader->read_long();

            // payload + ch
            $this->wait_frame_reader->reuse($this->input->read(AMQPReader::OCTET + (int) $size));

            $payload = $this->wait_frame_reader->read($size);
            $ch = $this->wait_frame_reader->read_octet();

        } catch (AMQPTimeoutException $e) {
            $this->input->setTimeout($currentTimeout);
            throw $e;
        }

        $this->input->setTimeout($currentTimeout);

        if ($ch != 0xCE) {
            throw new AMQPRuntimeException(sprintf(
                'Framing error, unexpected byte: %x',
                $ch
            ));
        }

        return array($frame_type, $channel, $payload);
    }
```

SocketIO.php
```php
    public function read($n)
    {
        $res = '';
        $read = 0;

        $buf = socket_read($this->sock, $n);
        while ($read < $n && $buf !== '' && $buf !== false) {
            // Null sockets are invalid, throw exception
            if (is_null($this->sock)) {
                throw new AMQPRuntimeException(sprintf(
                    'Socket was null! Last SocketError was: %s',
                    socket_strerror(socket_last_error())
                ));
            }

            $read += mb_strlen($buf, 'ASCII');
            $res .= $buf;
            $buf = socket_read($this->sock, $n - $read);
        }

        if (mb_strlen($res, 'ASCII') != $n) {
            throw new AMQPIOException(sprintf(
                'Error reading data. Received %s instead of expected %s bytes',
                mb_strlen($res, 'ASCII'),
                $n
            ));
        }

        return $res;
    }
```

As you can see, AMQPReader::OCTET + AMQPReader::SHORT + AMQPReader::LONG = 7.

this value will be passed to the read function wich will try to read from a socket and according to php documentation:
"socket_read() returns a zero length string ("") when there is no more data to read."

when the queue is empty and rabbit returns nothing a empty string is return from socket_read wich is not 7 bytes long, then the error occurs. I don't know if its a problem within my environment, its a stock ubuntu with no extra ppas. this also happened on a docker container with the same distro and packages.

My environment is the following
Ubuntu 16.10
php 7.0.15
symfony 3.2
rabbitmq bundle: ^1.12
php-socket installed form ubuntu repo, im not using any ppa
Rabbitmq:
```
{running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.5.7"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.5.7"},
      {webmachine,"webmachine","1.10.3-rmq3.5.7-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.5.7-git680dba8"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.5.7"},
      {rabbit,"RabbitMQ","3.5.7"},
      {mnesia,"MNESIA  CXC 138 12","4.13.4"},
      {amqp_client,"RabbitMQ AMQP Client","3.5.7"},
      {xmerl,"XML parser","1.3.10"},
      {os_mon,"CPO  CXC 138 46","2.4"},
      {inets,"INETS  CXC 138 49","6.2.4"},
      {sasl,"SASL  CXC 138 11","2.7"},
      {stdlib,"ERTS  CXC 138 10","2.8"},
      {kernel,"ERTS  CXC 138 10","4.2"}]},
```

I hope this info is usefull, i really use this lib a lot on my projects and im very gratefull to it.

**Comment by michaelklishin** [comment] 2017-04-27 07:05
Can you please go into a bit more detail than simply claiming that "this is a bug" and what the expected behavior is? Sorry but simply dumping some code and claiming that there is a bug is not enough information for many.

In particular I do not understand the line about "when the queue is empty rabbit returns nothing an empty string is returned from socket_read". RabbitMQ does not send empty strings when a queue is empty. Even when it's not, due to the way sockets work you can get an empty string from a read.

Most clients retry when that happens up to a point. It is up to [AMQP 0-9-1 heartbeats](http://rabbitmq.com/heartbeats.html) to detect connection failure, or reasonable TCP socket settings such as read timeouts.

So how exactly do you expect socket reads that return no data to be handled?

**Comment by hairyhum** [comment] 2017-05-15 17:07
This looks like an issue in error reporting. I can reproduce this error, but what actually happens is that `$buf` is `FALSE`, so it's a socket error. While it's not an error, but a `EAGAIN` message, which was caused by read timeout (3 sec by default).
To avoid this error, `select()` should be called on the socket before running `socket_read()`, but `select()` without a timeout could be unsupported in some versions of PHP. https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/AMQPReader.php#L119

**Comment by hairyhum** [comment] 2017-05-15 17:08
Of course the actual error should be reported if there is one, instead of "Error reading data..."

**Comment by jhonatanTeixeira** [comment] 2017-05-15 17:33
Sorry if my first report wasn't a proper one. I was into deep presure to deliver this project and in a hurry to report. But now i've edited the report to have more information.

i really dont know why, but as you can see on the code the socket itself does an empty read, i even dumped the $buf variable to see that, its returning the empty string as the php documentation says it would, but then theres that if with mb_strlen wich is compared to the 7 byte passed down(and heres my lack of knowledge, i dont know the reason for that check).

I really dont have what it takes to try and fix this issue that happens pehaps only on my project.

I really love this lib

**Comment by hairyhum** [comment] 2017-05-16 08:21
@jhonatanTeixeira have you tried to get `socket_last_error` when you get an empty `$buf`? Just to verify that we're getting the same error.

**Comment by HonzaMac** [comment] 2017-08-01 16:35
I have same problem as described here. Is hearbeat solution for this?

**Comment by lukebakken** [comment] 2018-01-16 14:21
Fixed in #484

**Closed by lukebakken** 2018-01-16 14:21 UTC

**Comment by kgrosvenor** [comment] 2018-05-10 11:35
This happens when my queue turns empty, how do i fix - this is definitely a bug ???

**Comment by rtyshyk** [comment] 2018-08-31 15:18
@kgrosvenor > This happens when my queue turns empty, how do i fix - this is definitely a bug ???
did you find solution? I have the same..

**Comment by kgrosvenor** [comment] 2018-08-31 16:30
I ended up re writing my code in c# driver, it's much better and you can make your consumers async too, the php lib is buggy imo

**Comment by lukebakken** [comment] 2018-08-31 18:02
This project is open-source and welcomes bug fixes and improvements. The RabbitMQ core team maintains this project on a volunteer basis and hopes to be able to spend more time on it soon.

**Comment by jhonatanTeixeira** [comment] 2018-08-31 18:06
@krogsvenor be happy. But don't come here tryimg to start a flamewar. Yours is an unecessary comment
